typography_spectrum: 0.624054386978969
color:
  brandStrength: 0.8837673396337777
  lightness: 0.33825450646691024
  saturation: 0.7387768994085491
  rhythmicContrast: 0.10769737767986953
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/9eefaf69-e747-4075-947a-05fffce922ee.jpg
layout_spectrum: 0.6940963098313659
author:
  name: Colleen Kudo
  email: colleen@oceangirlproject.com
  url: www.oceangirlproject.com
name: Ocean Girl Project Blog
