typography_spectrum: 0.33570677042007446
color:
  brandStrength: 0.7918962927069515
  lightness: 0.7856835077982396
  saturation: 0.9389923037961125
  rhythmicContrast: 0.027397506404668093
  brandColors:
    - '#04BFBF'
    - '#CAFCD8'
    - '#F7E967'
    - '#A9CF54'
    - '#588F27'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/9eefaf69-e747-4075-947a-05fffce922ee.jpg
layout_spectrum: 0.8746149106882513
author:
  name: Colleen Kudo
  email: colleen@oceangirlproject.com
  url: www.oceangirlproject.com
name: Ocean Girl Project Blog
