typography_spectrum: 0.624054386978969
color:
  brandStrength: 0.6425238414667547
  lightness: 0.8473719717003405
  saturation: 0.19175225868821144
  rhythmicContrast: 0.34036546503193676
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/9eefaf69-e747-4075-947a-05fffce922ee.jpg
layout_spectrum: 0.6940963098313659
author:
  name: Colleen Kudo
  email: colleen@oceangirlproject.com
  url: www.oceangirlproject.com
name: Ocean Girl Project Blog
